# Ref:
#   https://cloud.google.com/build/docs/building-leaner-containers
steps:
  - name: gcr.io/cloud-builders/docker
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/make:latest',
      '-t', 'gcr.io/$PROJECT_ID/make:gitcommit-$COMMIT_SHA',
      '.'
    ]
images:
  - 'gcr.io/$PROJECT_ID/make:latest'
  - 'gcr.io/$PROJECT_ID/make:gitcommit-$COMMIT_SHA'
timeout: 600s
